# Generated by Django 2.0.7 on 2018-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=60)),
                ('tableTitle', models.CharField(max_length=60)),
                ('billNum', models.CharField(max_length=60)),
                ('incomingDate', models.CharField(max_length=60)),
                ('outDate', models.CharField(max_length=60)),
                ('settlementDate', models.CharField(max_length=60)),
                ('worker', models.CharField(max_length=60)),
                ('licensePlate', models.CharField(max_length=60)),
                ('carModel', models.CharField(max_length=60)),
                ('fixType', models.CharField(max_length=60)),
                ('incomingMileage', models.CharField(max_length=60)),
                ('carOwner', models.CharField(max_length=60)),
                ('carContact', models.CharField(max_length=60)),
                ('fixedLine', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=60)),
                ('carFrameCode', models.CharField(max_length=60)),
                ('engineCode', models.CharField(max_length=60)),
                ('selfEditedCode', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=300)),
                ('maintenanceFees', models.CharField(blank=True, max_length=40, null=True)),
                ('materialFees', models.CharField(blank=True, max_length=40, null=True)),
                ('allMoneyChina', models.CharField(blank=True, max_length=60, null=True)),
                ('allMoney', models.CharField(blank=True, max_length=40, null=True)),
                ('telePhone', models.CharField(blank=True, max_length=40, null=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.CharField(blank=True, max_length=10, null=True)),
                ('mainProject', models.CharField(blank=True, max_length=10000, null=True)),
                ('materialProject', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainList', models.CharField(max_length=60)),
                ('materialList', models.CharField(max_length=60)),
                ('unt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
